DROP TABLE `analyses`;--> statement-breakpoint
DROP TABLE `breakoutScans`;--> statement-breakpoint
DROP TABLE `bulkSessionAnalyses`;--> statement-breakpoint
DROP TABLE `bulkSessions`;--> statement-breakpoint
DROP TABLE `capitalEvents`;--> statement-breakpoint
DROP TABLE `channelVideos`;--> statement-breakpoint
DROP TABLE `deepAnalysisCache`;--> statement-breakpoint
DROP TABLE `engineChatHistory`;--> statement-breakpoint
DROP TABLE `holding2`;--> statement-breakpoint
DROP TABLE `hourlySnapshots`;--> statement-breakpoint
DROP TABLE `ibkrConidCache`;--> statement-breakpoint
DROP TABLE `ibkrConnectionLog`;--> statement-breakpoint
DROP TABLE `ibkrSettings`;--> statement-breakpoint
DROP TABLE `journalEvents`;--> statement-breakpoint
DROP TABLE `knowledgeBase`;--> statement-breakpoint
DROP TABLE `labDailyLogs`;--> statement-breakpoint
DROP TABLE `labExecutionLogs`;--> statement-breakpoint
DROP TABLE `labSimulations`;--> statement-breakpoint
DROP TABLE `labTrades`;--> statement-breakpoint
DROP TABLE `llmScanCache`;--> statement-breakpoint
DROP TABLE `localUsers`;--> statement-breakpoint
DROP TABLE `masterKnowledge`;--> statement-breakpoint
DROP TABLE `moneyTransfers`;--> statement-breakpoint
DROP TABLE `orderAuditLog`;--> statement-breakpoint
DROP TABLE `otpCodes`;--> statement-breakpoint
DROP TABLE `paperEntryLock`;--> statement-breakpoint
DROP TABLE `paperEquitySnapshots`;--> statement-breakpoint
DROP TABLE `paperLedger`;--> statement-breakpoint
DROP TABLE `paperPenaltyBox`;--> statement-breakpoint
DROP TABLE `paperPositions`;--> statement-breakpoint
DROP TABLE `paperReentryWatch`;--> statement-breakpoint
DROP TABLE `paperTickerWallet`;--> statement-breakpoint
DROP TABLE `paperTightExitAudit`;--> statement-breakpoint
DROP TABLE `paperTrades`;--> statement-breakpoint
DROP TABLE `parkingLotConfig`;--> statement-breakpoint
DROP TABLE `portfolioAccounts`;--> statement-breakpoint
DROP TABLE `portfolioAnalysis`;--> statement-breakpoint
DROP TABLE `portfolioChatMessages`;--> statement-breakpoint
DROP TABLE `portfolioHoldings`;--> statement-breakpoint
DROP TABLE `portfolioSnapshots`;--> statement-breakpoint
DROP TABLE `priceAlerts`;--> statement-breakpoint
DROP TABLE `priceCache`;--> statement-breakpoint
DROP TABLE `priceCacheBlob`;--> statement-breakpoint
DROP TABLE `proficiencyMatrix`;--> statement-breakpoint
DROP TABLE `systemLogs`;--> statement-breakpoint
DROP TABLE `systemSettings`;--> statement-breakpoint
DROP TABLE `telegramMonitorGroups`;--> statement-breakpoint
DROP TABLE `telegramMonitorMessages`;--> statement-breakpoint
DROP TABLE `tradePositions`;--> statement-breakpoint
DROP TABLE `tradingDiary`;--> statement-breakpoint
DROP TABLE `tvAlerts`;--> statement-breakpoint
DROP TABLE `tvWebhookSettings`;--> statement-breakpoint
DROP TABLE `userAssets`;--> statement-breakpoint
DROP TABLE `userSettings`;--> statement-breakpoint
DROP TABLE `watchlistDismissed`;--> statement-breakpoint
ALTER TABLE `users` DROP COLUMN `totpSecret`;